/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import Proyecto1.MostrarInterfaz;

/**
 *
 * @author Edgar Torres
 */
public class Menu extends javax.swing.JFrame {
    
    MostrarInterfaz mostrar = new MostrarInterfaz();

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Eliminar = new javax.swing.JButton();
        Cargar = new javax.swing.JButton();
        Conectar = new javax.swing.JButton();
        Guardar = new javax.swing.JButton();
        Iniciar = new javax.swing.JButton();
        Cuidad5 = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        Menu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Eliminar.setBackground(new java.awt.Color(51, 255, 204));
        Eliminar.setFont(new java.awt.Font("Swis721 Blk BT", 1, 14)); // NOI18N
        Eliminar.setText("Eliminar Ciudad");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        getContentPane().add(Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 160, 50));

        Cargar.setBackground(new java.awt.Color(51, 255, 204));
        Cargar.setFont(new java.awt.Font("Swis721 Blk BT", 1, 14)); // NOI18N
        Cargar.setText("Cargar Grafo");
        Cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarActionPerformed(evt);
            }
        });
        getContentPane().add(Cargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 160, 50));

        Conectar.setBackground(new java.awt.Color(51, 255, 204));
        Conectar.setFont(new java.awt.Font("Swis721 Blk BT", 1, 14)); // NOI18N
        Conectar.setText("Conectar Ciudad");
        Conectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConectarActionPerformed(evt);
            }
        });
        getContentPane().add(Conectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 160, 50));

        Guardar.setBackground(new java.awt.Color(51, 255, 204));
        Guardar.setFont(new java.awt.Font("Swis721 Blk BT", 1, 14)); // NOI18N
        Guardar.setText("Guardar Grafo");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        getContentPane().add(Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 160, 50));

        Iniciar.setBackground(new java.awt.Color(51, 255, 204));
        Iniciar.setFont(new java.awt.Font("Swis721 Blk BT", 1, 14)); // NOI18N
        Iniciar.setText("Iniciar simulación");
        Iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarActionPerformed(evt);
            }
        });
        getContentPane().add(Iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 160, 50));

        Cuidad5.setBackground(new java.awt.Color(51, 255, 204));
        Cuidad5.setFont(new java.awt.Font("Swis721 Blk BT", 1, 14)); // NOI18N
        Cuidad5.setText("Agregar Ciudad");
        Cuidad5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cuidad5ActionPerformed(evt);
            }
        });
        getContentPane().add(Cuidad5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 160, 50));

        Salir.setBackground(new java.awt.Color(255, 204, 51));
        Salir.setFont(new java.awt.Font("Swis721 Blk BT", 1, 14)); // NOI18N
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, 160, 50));

        Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/2.png"))); // NOI18N
        getContentPane().add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 777, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarActionPerformed
        Menu a = new Menu ();
        a.setVisible(true);
        this.setVisible(false);
        
        mostrar.Grafo().display();
    }//GEN-LAST:event_IniciarActionPerformed

    private void Cuidad5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cuidad5ActionPerformed
        Agregar a = new Agregar ();
        a.setVisible(true);
        this.setVisible(false); 
    }//GEN-LAST:event_Cuidad5ActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
          Delete a = new Delete ();
        a.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_EliminarActionPerformed

    private void CargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarActionPerformed
           Cargar a = new Cargar ();
        a.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_CargarActionPerformed

    private void ConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConectarActionPerformed
   Conectar a = new Conectar();
        a.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_ConectarActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
           Guardar a = new Guardar ();
        a.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_GuardarActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        System.exit(WIDTH);
    }//GEN-LAST:event_SalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cargar;
    private javax.swing.JButton Conectar;
    private javax.swing.JButton Cuidad5;
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton Guardar;
    private javax.swing.JButton Iniciar;
    private javax.swing.JLabel Menu;
    private javax.swing.JButton Salir;
    // End of variables declaration//GEN-END:variables
}
